Perf/neo4j performance
datahub-project/datahub pull request #10415
Opened 2024-05-02 10:57 UTC by pashashaik-mms

## Checklist

- [X] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- ~[ ] Links to related issues (if applicable)~
- [X] Tests for the changes have been added/updated (if applicable)
- ~[ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.~
- ~[ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)~

2024-05-02 11:38 UTC, pashashaik-mms commented
This PR introduces an optimization to the Neo4j querying process within our Datahub project. Previously, our Neo4j queries did not specify node labels during the match phase, which resulted in scanning all nodes in the database. This approach was inefficient, especially for large datasets. By integrating dynamic node labels into our match queries, we significantly improve query performance by leveraging Neo4j's ability to use indexes more effectively.

**Node Label Integration:** Modified the Neo4j queries wherever applicable and now, the query explicitly targets nodes with the specified label, reducing the search space and improving performance.

**Performance:** By applying node labels directly in our match clauses, the database engine can optimize node lookups using existing indexes, thus speeding up the query execution by reducing the number of nodes scanned.
**Scalability:** These improvements make our database queries more scalable, handling larger datasets more efficiently.
**Maintainability:** This change also enhances the clarity of our queries, making them more understandable at a glance, which benefits new contributors and maintainers alike.

You can find the screenshot attached comparing the profile result:

**Profile WITHOUT NODELABEL query**
![image](https://github.com/datahub-project/datahub/assets/85875002/6aa0ca8b-4a78-44c5-8936-23a564dd0520)

**Profile WITH NODELABEL query**
![image](https://github.com/datahub-project/datahub/assets/85875002/d8093cbc-be88-4a5c-89f4-2c94f14c2166)

2024-05-22 16:45 UTC, david-leifker approved these changes

2024-05-22 16:49 UTC, RyanHolstien approved these changes

2024-05-22 21:03 UTC, david-leifker requested changes
There are broken tests with `./gradlew :metadata-io:test`

2024-05-23 04:55 UTC, pankajmahato-visa commented
@pashashaik-mms 
 Run './gradlew :metadata-io:spotlessApply' to fix these violations.

2024-05-23 15:20 UTC, pashashaik-mms commented
@RyanHolstien @david-leifker Could you please approve it as I had fixed the changes. It was a formatting issue and hence the build was failing and so are the unit-tests. I fixed it now and would need your approval.

2024-05-23 15:20 UTC, pashashaik-mms commented
> Could you please approve it as I had fixed the changes. It was a formatting issue and hence the build was failing and so are the unit-tests. I fixed it now and would need your approval.

2024-05-24 10:57 UTC, deepgarg-visa commented
@pashashaik-mms , as mentions [here](https://github.com/datahub-project/datahub/actions/runs/9198346655/job/25300909269?pr=10415#step:6:3427)

the below error is occurring because in testcases [here](https://github.com/datahub-project/datahub/blob/master/metadata-io/src/test/java/com/linkedin/metadata/graph/GraphServiceTestBase.java#L1108), "sourceEntityFilter" is passed as null and because of that the variable "srcNodeLabel" in method "findRelatedEntities" is not setting having a default value of blank, which results in the below query which is not correct.

`MATCH (src: )-[r:DownstreamOf ]-(dest ) WHERE left(type(r), 2)<>'r_'  RETURN dest, type(r) SKIP $offset LIMIT $count"`

Please also handle the case where variable "sourceEntityFilter" in method "findRelatedEntities" can be null or empty

`metadata-io > nonsearch > com.linkedin.metadata.graph.dgraph.DgraphGraphServiceTest > testFindRelatedEntitiesDestinationType[11](dataset, [HasOwner], {or=[], direction=UNDIRECTED}, [RelatedEntity(relationshipType=HasOwner, urn=urn:li:dataset:(urn:li:dataPlatform:type,SampleDataset1,PROD), via=null), RelatedEntity(relationshipType=HasOwner, urn=urn:li:dataset:(urn:li:dataPlatform:type,SampleDataset2,PROD), via=null), RelatedEntity(relationshipType=HasOwner, urn=urn:li:dataset:(urn:li:dataPlatform:type,SampleDataset3,PROD), via=null), RelatedEntity(relationshipType=HasOwner, urn=urn:li:dataset:(urn:li:dataPlatform:type,SampleDataset4,PROD), via=null)]) STANDARD_ERROR
    org.neo4j.bolt.protocol.common.fsm.error.TransactionStateTransitionException: Invalid input ')': expected "%", "(" or an identifier (line 1, column 13 (offset: 12))
    "MATCH (src: )-[r:DownstreamOf ]-(dest ) WHERE left(type(r), 2)<>'r_'  RETURN dest, type(r) SKIP $offset LIMIT $count"`

2024-05-24 14:22 UTC, pashashaik-mms commented
> @pashashaik-mms , as mentions [here](https://github.com/datahub-project/datahub/actions/runs/9198346655/job/25300909269?pr=10415#step:6:3427)
> 
> the below error is occurring because in testcases [here](https://github.com/datahub-project/datahub/blob/master/metadata-io/src/test/java/com/linkedin/metadata/graph/GraphServiceTestBase.java#L1108), "sourceEntityFilter" is passed as null and because of that the variable "srcNodeLabel" in method "findRelatedEntities" is not setting having a default value of blank, which results in the below query which is not correct.
> 
> `MATCH (src: )-[r:DownstreamOf ]-(dest ) WHERE left(type(r), 2)<>'r_' RETURN dest, type(r) SKIP $offset LIMIT $count"`
> 
> Please also handle the case where variable "sourceEntityFilter" in method "findRelatedEntities" can be null or empty
> 
> `metadata-io > nonsearch > com.linkedin.metadata.graph.dgraph.DgraphGraphServiceTest > testFindRelatedEntitiesDestinationType[11](dataset, [HasOwner], {or=[], direction=UNDIRECTED}, [RelatedEntity(relationshipType=HasOwner, urn=urn:li:dataset:(urn:li:dataPlatform:type,SampleDataset1,PROD), via=null), RelatedEntity(relationshipType=HasOwner, urn=urn:li:dataset:(urn:li:dataPlatform:type,SampleDataset2,PROD), via=null), RelatedEntity(relationshipType=HasOwner, urn=urn:li:dataset:(urn:li:dataPlatform:type,SampleDataset3,PROD), via=null), RelatedEntity(relationshipType=HasOwner, urn=urn:li:dataset:(urn:li:dataPlatform:type,SampleDataset4,PROD), via=null)]) STANDARD_ERROR org.neo4j.bolt.protocol.common.fsm.error.TransactionStateTransitionException: Invalid input ')': expected "%", "(" or an identifier (line 1, column 13 (offset: 12)) "MATCH (src: )-[r:DownstreamOf ]-(dest ) WHERE left(type(r), 2)<>'r_' RETURN dest, type(r) SKIP $offset LIMIT $count"`

FIXED NOW

2024-05-24 14:22 UTC, pashashaik-mms commented
@deepgarg-visa fixed now. Could you please check and approve it. Its been waiting a while now.

2024-05-24 14:32 UTC, deepgarg-visa commented
@pashashaik-mms are all metadata-io testcase passed ?

2024-05-24 16:46 UTC, deepgarg-visa commented on metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java
> +      baseStatementString =
this is common in both if and else. It can be put outside

2024-05-29 07:30 UTC, pashashaik-mms commented on metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java
> +    String matchTemplate = "";
After a short vacation, I could see that you had already these changes. I made it in sync. What should be considered for this PR? Should we close it? or keep it for approval?

2024-05-29 14:58 UTC, closed without merging

2024-05-29 14:58 UTC, david-leifker commented
Looks like the changes were added in a different PR, closing this one. Thanks!