fix(ingestion/airflow-plugin): bumping up the openlineage-airflow version
datahub-project/datahub pull request #10457
Opened 2024-05-08 11:05 UTC by dushayntAW

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

2024-05-08 16:07 UTC, hsheth2 approved these changes

2024-05-08 16:54 UTC, hsheth2 requested changes

2024-05-08 16:54 UTC, hsheth2 commented on metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/client/airflow_generator.py
> +        if datajob is None and ti.task is not None:
```suggestion
        if datajob is None:
            assert ti.task is not None
```

2024-05-08 16:54 UTC, hsheth2 commented on metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/client/airflow_generator.py
> +        assert datajob is not None
can be removed

2024-05-08 16:54 UTC, hsheth2 commented on metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/client/airflow_generator.py
> +        if datajob is None and ti.task is not None:
same as above

2024-05-08 16:54 UTC, hsheth2 commented on metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/datahub_listener.py
> -        dag: "DAG" = task.dag  # type: ignore[assignment]
add an `assert task is not None`, and remove the other changes

2024-05-08 17:48 UTC, hsheth2 commented on metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/datahub_listener.py
> +        if task is not None:
No longer needed

2024-05-08 17:48 UTC, hsheth2 commented on metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/datahub_listener.py
> +        if task is not None:
No longer needed

2024-05-09 07:30 UTC, anshbansal commented
Failure in nested domains is unrelated

2024-05-09 07:30 UTC, merged