feat(entity-registry): Enforce Field Path V2 uniqueness check during ingestion
datahub-project/datahub pull request #10477
Opened 2024-05-09 21:32 UTC by pedro93

Adds check in GMS when processing `schemaMetadata` aspects that all field paths are unique. 
If that is not the case, reject the MCP. 
The reason for this validator is that the UI will not be able to render schemas correctly if _field path ids_ are not unique.

## Checklist

- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

2024-05-10 13:03 UTC, david-leifker commented on entity-registry/src/main/java/com/linkedin/metadata/aspect/validation/FieldPathValidator.java
> +public class FieldPathValidator extends AspectPayloadValidator {
This needs an entry in the entity-registry to be activated.

2024-05-10 15:56 UTC, pedro93 commented
Failing CI seems unrelated.

2024-05-10 16:43 UTC, david-leifker requested changes
Handle patch or drop it as a supported operation please.

2024-06-28 21:43 UTC, jjoyce0510 commented
@david-leifker Let's get this one followed up on pls. Cheers!

2024-07-31 16:29 UTC, david-leifker commented
There was some discussion around whether it was better to throw and exception here or to drop the duplicate field. I think the conclusion was to drop the duplicate field instead. @pedro93 - please let me know if I've mis-remember the conversation around this validator or not. If not, I'd close this PR.

2024-07-31 16:32 UTC, pedro93 commented
> There was some discussion around whether it was better to throw and exception here or to drop the duplicate field. I think the conclusion was to drop the duplicate field instead. @pedro93 - please let me know if I've mis-remember the conversation around this validator or not. If not, I'd close this PR.

I vaguely recall us wanting to throw an exception in the future **after** our connectors have been fixed. Silently dropping the duplicate fields was meant as a stop gap measure. @hsheth2 please confirm.

2024-07-31 18:26 UTC, hsheth2 commented
Based on our telemetry, about ~0.1% of ingestion runs produce duplicate field paths

Among the ingestions that needed to drop at least one field, it's a fairly small fraction of assets are actually impacted 
<img width="311" alt="image" src="https://github.com/user-attachments/assets/0ea7e30a-d669-49f3-b770-84305ad20a9f">

Given that this is a fairly small problem for ingestion and that ingestion has protections in place now, we're clear to include the server-side validation in the 0.13.4 release.

2024-10-14 22:43 UTC, david-leifker commented
Replaced by https://github.com/datahub-project/datahub/pull/11619

2024-10-14 22:43 UTC, closed without merging