feat(ingest/salesforce): helpful error messages on failure
datahub-project/datahub pull request #11266
Opened 2024-08-29 11:05 UTC by mayurinehate

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

2024-08-29 14:57 UTC, skrydal commented on metadata-ingestion/src/datahub/ingestion/source/salesforce.py
> +            if "API_CURRENTLY_DISABLED" in str(e):
This string will be present **only if** the `Exception` is actually:
`simple_salesforce.exceptions.SalesforceAuthenticationFailed` maybe we can catch is explicitly?

2024-08-29 15:08 UTC, skrydal commented on metadata-ingestion/src/datahub/ingestion/source/salesforce.py
> +                yield from self.get_salesforce_object_workunits(sObject)
Awesome 👍

2024-08-29 15:13 UTC, skrydal requested changes
Looks very good, left some comments about clarification of error messages trigger.

2024-08-30 05:35 UTC, mayurinehate commented on metadata-ingestion/src/datahub/ingestion/source/salesforce.py
> +                "Please set `is_sandbox: True` in recipe if this is sandbox account."
I'm not quite sure if salesforce sandbox url follows any specific structure. Do you have any resource that confirms that instance url can be used to identify whether this is sandbox account ?

2024-08-30 05:50 UTC, mayurinehate commented on metadata-ingestion/src/datahub/ingestion/source/salesforce.py
> +                "Please set `is_sandbox: True` in recipe if this is sandbox account."
Noticed that its general pattern to use "sandbox" in name, so in favour of best practice, will change this handling to check whether "sandbox" is present in url, before showing this message.

2024-08-30 11:12 UTC, skrydal approved these changes
LGTM

2024-09-05 16:47 UTC, hsheth2 approved these changes

2024-09-05 16:47 UTC, merged