fix(ingestion/transformer): extend pattern_add_dataset_ownership transformer to support containers
datahub-project/datahub pull request #11375
Opened 2024-09-13 16:10 UTC by sagar-salvi-apptware

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

2024-09-18 00:06 UTC, eboneil approved these changes

2024-09-18 00:41 UTC, hsheth2 requested changes
Needs tests

You can add or update tests in `tests/unit/test_transform_dataset.py`

2024-09-18 17:51 UTC, sagar-salvi-apptware commented
> add

Done, added TC for containers

2024-09-18 17:51 UTC, sagar-salvi-apptware commented
> Needs tests
> 
> You can add or update tests in `tests/unit/test_transform_dataset.py`

Done, added TC for containers

2024-09-23 19:31 UTC, hsheth2 approved these changes

2024-10-01 18:39 UTC, merged