fix(lint): fix yarn lint breakage from #11498
datahub-project/datahub pull request #11553
Opened 2024-10-07 20:39 UTC by shirshanka

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

2024-10-07 20:50 UTC, david-leifker approved these changes

2024-10-07 20:50 UTC, david-leifker requested changes
```
> Task :datahub-web-react:yarnLint
All matched files use Prettier code style!
$ tsc --noEmit
src/app/entity/shared/tabs/Dataset/Schema/utils/getFieldDescriptionDetails.ts(11,54): error TS2339: Property '0' does not exist on type 'DocumentationAssociation[] | undefined'.
error Command failed with exit code 2.
```

2024-10-07 22:41 UTC, david-leifker approved these changes

2024-10-07 23:32 UTC, merged

2024-10-08 09:03 UTC, Daniellundin048 reviewed
Thx