fix(ingestion/kafka): OAuth callback execution
datahub-project/datahub pull request #11900
Opened 2024-11-20 04:54 UTC by sid-acryl

Execute callback provided in `config.connection.consumer_config.oauth_cb `

```YAML
source:
  type: "kafka"
  config:
    # Set the custom schema registry implementation class
    schema_registry_class: "datahub.ingestion.source.confluent_schema_registry.ConfluentSchemaRegistry"
    # Coordinates
    connection:
      bootstrap: "broker:9092"
      schema_registry_url: http://localhost:8081
      consumer_config:
        security.protocol: "SASL_PLAINTEXT"
        sasl.mechanism: "OAUTHBEARER"
        oauth_cb: "oauth:create_token"
# sink configs
```

2024-11-20 06:45 UTC, hsheth2 requested changes
CI appears to be failing

2024-11-20 17:33 UTC, hsheth2 submitted a review, later dismissed
Docs generation appears to be failing - likely something isn't properly escaped in the markdown

2024-11-21 03:40 UTC, sid-acryl commented on metadata-ingestion/src/datahub/ingestion/source/kafka/kafka_consumer_config.py
> +class CallableConsumerConfig(Consumer):
Initial structure was different, later simplified it. Removed the (Consumer)

2024-11-22 07:37 UTC, anshbansal approved these changes

2024-11-22 07:38 UTC, merged