fix(ingest/looker): Add flag for Looker metadata extraction
datahub-project/datahub pull request #12205
Opened 2024-12-23 09:55 UTC by sagar-salvi-apptware

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

2024-12-23 10:38 UTC, mayurinehate requested changes

2024-12-23 10:38 UTC, mayurinehate commented on metadata-ingestion/src/datahub/sql_parsing/tool_meta_extractor.py
> +    looker_mapping_missing = False
```suggestion
    looker_user_mapping_missing: Optional[bool] = None
```

2024-12-23 10:38 UTC, mayurinehate commented on metadata-ingestion/src/datahub/sql_parsing/tool_meta_extractor.py
> +            report.looker_mapping_missing = True
```suggestion
            report.looker_user_mapping_missing = True
```

2024-12-23 10:38 UTC, mayurinehate commented on metadata-ingestion/src/datahub/sql_parsing/tool_meta_extractor.py
> +    looker_mapping_missing = False
This would help differentiate default value from assigned value.

2024-12-23 12:20 UTC, mayurinehate approved these changes

2024-12-24 19:27 UTC, hsheth2 approved these changes

2024-12-24 19:27 UTC, merged