feat(businessAttribute): generate platform events on association/removal of businessattributes with schemaField
datahub-project/datahub pull request #12224
Opened 2024-12-25 12:43 UTC by deepgarg-visa

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

2024-12-26 16:37 UTC, david-leifker commented on metadata-io/src/main/java/com/linkedin/metadata/timeline/eventgenerator/BusinessAttributesChangeEventGenerator.java
> +package com.linkedin.metadata.timeline.eventgenerator;
This class requires some test coverage.

2024-12-26 16:38 UTC, david-leifker requested changes
Thanks! The changes here look good to me. The only request is to add some unit tests around the new `BusinessAttributesChangeEventGenerator` class.

2024-12-27 14:31 UTC, deepgarg-visa commented on metadata-io/src/main/java/com/linkedin/metadata/timeline/eventgenerator/BusinessAttributesChangeEventGenerator.java
> +package com.linkedin.metadata.timeline.eventgenerator;
@david-leifker added

2024-12-27 19:24 UTC, david-leifker approved these changes

2024-12-27 20:19 UTC, merged