docs(undo_by_filter): Document un-soft-delete commands in delete-metadata.md
datahub-project/datahub pull request #12251
Opened 2024-12-31 17:29 UTC by gabe-lyons

See title. I hear questions about this often.

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

2024-12-31 18:02 UTC, hsheth2 approved these changes

2025-01-01 06:11 UTC, anshbansal requested changes

2025-01-01 06:11 UTC, anshbansal commented on docs/how/delete-metadata.md
> +datahub delete undo_by_filter --urn "urn:li:dataset:(urn:li:dataPlatform:hive,fct_users_deleted,PROD)"
command is `undo-by-filter`. `undo_by_filter` is method name

2025-01-02 22:42 UTC, gabe-lyons commented on docs/how/delete-metadata.md
> +datahub delete undo_by_filter --urn "urn:li:dataset:(urn:li:dataPlatform:hive,fct_users_deleted,PROD)"
@anshbansal fixed

2025-01-02 23:56 UTC, merged