feat(ingest): simplify event IDs for function invocations
datahub-project/datahub pull request #4398
Opened 2022-03-12 17:47 UTC by kevinhu

## Checklist
- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

2022-03-14 18:22 UTC, hsheth2 commented on metadata-ingestion/src/datahub/telemetry/telemetry.py
> +            telemetry_instance.ping(
this except clause should be before the `except Exception as e` - otherwise it'll never get hit

2022-03-14 18:22 UTC, hsheth2 commented on metadata-ingestion/src/datahub/telemetry/telemetry.py
> +                {action: action, "status": "completed"},
```suggestion
                {"action": action, "status": "completed"},
```

2022-03-14 18:22 UTC, hsheth2 commented on metadata-ingestion/src/datahub/telemetry/telemetry.py
> +                {action: action, "status": "completed"},
ditto below

2022-03-23 17:47 UTC, rslanka requested changes
Hi @kevinhu, could you please resolve the merge conflicts?

2022-03-23 17:56 UTC, rslanka commented on metadata-ingestion/src/datahub/telemetry/telemetry.py
>              if e.code == 0:
Should we check against `None` as well (see [documentation](https://docs.python.org/3/library/exceptions.html?highlight=systemexit#SystemExit.code))?

2022-03-23 17:57 UTC, rslanka commented on metadata-ingestion/src/datahub/telemetry/telemetry.py
>                  sys.exit(0)
why not just raise `e`?

2022-03-23 17:58 UTC, rslanka commented on metadata-ingestion/src/datahub/telemetry/telemetry.py
>                  sys.exit(e.code)
why not just raise `e`?

2022-03-23 17:58 UTC, rslanka commented on metadata-ingestion/src/datahub/telemetry/telemetry.py
>              sys.exit(0)
Should this be really treated as successful exit? `raise e` instead?

2022-03-23 18:36 UTC, rslanka commented on metadata-ingestion/src/datahub/telemetry/telemetry.py
> +            if e.code == 0 or e.code is None:
```suggestion
            if not e.code:
```

2022-03-23 18:49 UTC, rslanka approved these changes
LGTM!

2022-03-23 19:52 UTC, merged

2022-03-24 11:45 UTC, anshbansal commented
FYI https://github.com/datahub-project/datahub/pull/4479 to reduce log levels