feat(dbt): enable dbt read artifacts from s3
datahub-project/datahub pull request #4935
Opened 2022-05-17 21:02 UTC by BoyuanZhangDE

## Checklist
- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

2022-05-17 21:05 UTC, BoyuanZhangDE commented
- User can put s3 URI in the `manifest_path`, `catalog_path` or `sources_path`.
- `aws_region` here is `None` by default incase users don't want to use s3 URI.
- Not sure of the type annotation for `s3_client` so I put `"botocore.client.S3"`. Local linting was failed.

2022-05-23 18:30 UTC, shirshanka requested changes

2022-05-23 18:30 UTC, shirshanka commented on metadata-ingestion/src/datahub/ingestion/source/dbt.py
> +class DBTConfig(AwsSourceConfig, StatefulIngestionConfigBase):
Unfortunately `AwsSourceConfig` seems to bring in a bunch of stuff you don't really need to pull in. e.g. `database_pattern`, `table_pattern`, `env` etc. 

I suggest you refactor AwsSourceConfig into AwsConnectionConfig to extract that code out, and pull that in as an optional field into DBTConfig.

2022-05-25 05:38 UTC, shirshanka approved these changes

2022-05-25 08:57 UTC, merged