feat(ingestion): Make CorpUser ingestion optional in PowerBI source
datahub-project/datahub pull request #5335
Opened 2022-07-05 11:09 UTC by mohdsiddique

2022-07-06 16:43 UTC, shirshanka commented
@mohdsiddique : seems like there is a conflict with the main branch, so you might need to refresh your PR.

2022-07-07 08:57 UTC, mohdsiddique commented
@shirshanka merge conflict is resolved now.

2022-07-25 07:02 UTC, shirshanka commented
@mayurinehate : can you review this?

2022-07-27 15:39 UTC, jjoyce0510 commented
What's the status on this one?

2022-08-01 16:47 UTC, hsheth2 requested changes

2022-08-01 16:47 UTC, hsheth2 commented on metadata-ingestion/src/datahub/ingestion/source/powerbi.py
> +@capability(SourceCapability.OWNERSHIP, "Optionally enabled via configuration")
```suggestion
@capability(SourceCapability.OWNERSHIP, "On by default but can disabled by configuration")
```

2022-08-01 16:47 UTC, hsheth2 commented on metadata-ingestion/src/datahub/ingestion/source/powerbi.py
> +    override: CapabilitiesOverride = CapabilitiesOverride(extractOwnership=True)
I'm in favor of not introducing another level of nesting into the config. We have this pattern of bool flags throughout the codebase, for example the `include_views` option on the SQL sources. In those cases, it'd be pretty confusing to have `include_views` nested under a capabilities object but have the `view_patterns` still be top-level. Overall, I think we should keep the config flat unless there's a compelling reason not to.

2022-08-04 22:06 UTC, hsheth2 requested changes
minor nits but should be good to merge after this

2022-08-04 22:06 UTC, hsheth2 commented on metadata-ingestion/docs/sources/powerbi/powerbi_recipe.yml
> +      extractOwnership: true
update this

2022-08-04 22:06 UTC, hsheth2 commented on metadata-ingestion/docs/sources/powerbi/powerbi_recipe.yml
> +
nit - remove

2022-08-04 22:06 UTC, hsheth2 commented on metadata-ingestion/src/datahub/ingestion/source/powerbi.py
> +    include_ownerships: bool = pydantic.Field(
```suggestion
    extract_ownership: bool = pydantic.Field(
```

2022-08-05 19:53 UTC, hsheth2 approved these changes

2022-08-08 18:26 UTC, merged