feat(ingest/glue): handle error when generating s3 tags for virtual view tables
datahub-project/datahub pull request #5398
Opened 2022-07-15 04:39 UTC by timcosta

## Checklist
- [X] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [X] Links to related issues (if applicable)
- [X] Tests for the changes have been added/updated (if applicable)
- [X] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [X] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

2022-07-15 19:43 UTC, timcosta commented
Not really sure why CI failed, in the raw output the old and new values look the same to me - `urn:li:domain:Engineering`. Seems like maybe there's an added newline, but not sure if that's just the test output or an actual change. It also seems to be in an area of code that would be unaffected by this PR.

2022-07-18 15:31 UTC, shirshanka requested changes
Thanks for this @timcosta!
I've added some suggestions on simplifying this code change. I don't think we need to preserve compatibility with old behavior, instead we just need to fix how we are getting the bucket name to fetch tags.

2022-07-18 15:31 UTC, shirshanka commented on metadata-ingestion/src/datahub/ingestion/source/aws/glue.py
> +                    table["StorageDescriptor"]["Location"]
It seems to me that we just need to be more defensive about this. When a StorageDescriptor -> Location entry is not found, don't try to get tags for that bucket. Shouldn't be raising exception either. 

So something like:
```python
if table.get("StorageDescriptor",{}).get("Location"):
   bucket_name = s3_util.get_bucket_name(table["StorageDescriptor"]["Location"])...
...
else:
   return None
```

might be enough.

2022-07-18 15:31 UTC, shirshanka commented on metadata-ingestion/src/datahub/ingestion/source/aws/glue.py
> +    s3_tags_ignore_virtual_view_tables: Optional[bool] = Field(
Shouldn't need this flag to preserve old behavior...  I don't think anyone will want the old behavior.

2022-07-18 15:40 UTC, timcosta commented
Thanks for the comments @shirshanka, updated the branch to simply contain the logic fix rather than the flag to preserve backwards compatibility. I agree that people likely wouldnt want the original behavior, but it's usually easier to get PRs merged without changes that could be perceived as breaking :)

2022-07-18 16:10 UTC, shirshanka approved these changes
LGTM! Will merge once CI is green.

2022-07-20 03:43 UTC, merged