fix(bigquery-usage): fix dataset name for sharded table
datahub-project/datahub pull request #5412
Opened 2022-07-15 16:28 UTC by MugdhaHardikar-GSLab

## Checklist
- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

2022-07-18 12:38 UTC, treff7es requested changes

2022-07-19 05:14 UTC, MugdhaHardikar-GSLab commented on metadata-ingestion/src/datahub/ingestion/source/usage/bigquery_usage.py
> +        shortened_table_name = shortened_table_name.removesuffix("_*")
Done

2022-07-19 05:14 UTC, MugdhaHardikar-GSLab commented on metadata-ingestion/tests/unit/test_bigquery_usage_source.py
> +    table_ref = BigQueryTableRef("project-1234", "dataset-4567", "foo_2016*")
AS per discussion with @treff7es not taking this up in current PR.

2022-07-20 03:57 UTC, shirshanka approved these changes
LGTM

2022-07-20 03:59 UTC, merged

2022-07-20 07:50 UTC, treff7es reviewed
lgtm