feat(model): Add optional message field to auditstamp
datahub-project/datahub pull request #5611
Opened 2022-08-10 18:34 UTC by gabe-lyons

This allows us to track context around audit stamps.

## Checklist
- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

2022-08-10 19:12 UTC, shirshanka requested changes

2022-08-10 19:12 UTC, shirshanka commented on li-utils/src/main/pegasus/com/linkedin/common/AuditStamp.pdl
> +   * Additional message to keep track of in the event
doc string needs to be improved

2022-08-10 19:47 UTC, jjoyce0510 approved these changes
LGTM - Thanks!

2022-08-11 05:13 UTC, xiphl commented
This sounds super useful! i can think of the use cases when i programmatically emit updates to datahub already, thanks!

2022-08-11 17:10 UTC, gabe-lyons commented on li-utils/src/main/pegasus/com/linkedin/common/AuditStamp.pdl
> +   * Additional message to keep track of in the event
@shirshanka updated!

2022-08-11 20:32 UTC, shirshanka approved these changes
LGTM!

2022-08-11 20:48 UTC, merged