fix(ingest): proper null skip logic in serialization
datahub-project/datahub pull request #5749
Opened 2022-08-26 20:15 UTC by hsheth2

This reverts commit d549ff3.
## Checklist
- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

2022-08-27 02:57 UTC, shirshanka commented on metadata-ingestion/src/datahub/cli/check_cli.py
> +def canonicalize_mcp_file(json_file: str) -> None:
how about adding this as a flag to the existing check mce_file command?
maybe we should call it a different name in the light of mce -> mcp:
`datahub check metadata_file --json-file <metadata_events.json> --lintFix`

2022-08-27 03:01 UTC, shirshanka commented on metadata-ingestion/src/datahub/ingestion/run/pipeline.py
> +            logger.debug(f"Sink configured successfully. {self.sink.configured()}")
I think this is a pretty important log line. Only gets printed once in the execution of a recipe. Any particular reason to drop it to debug?

2022-08-27 03:02 UTC, shirshanka commented on metadata-ingestion/src/datahub/ingestion/sink/file.py
> +        # record_string = str(record_envelope.record)
seems like a remnant of reverting my previous commit. remove these?

2022-08-27 03:03 UTC, shirshanka requested changes
Seems like a few extra changes from the subject of the PR, intentional?

2022-08-29 16:26 UTC, hsheth2 commented
@shirshanka I'll split the unrelated changes into a separate PR - this one should be good to go now.

2022-08-29 23:34 UTC, shirshanka approved these changes
LGTM

2022-08-29 23:34 UTC, merged