feat(docs) Adds guide on how to use personal access tokens
datahub-project/datahub pull request #5873
Opened 2022-09-08 15:17 UTC by pedro93

## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [x] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

2022-09-09 14:27 UTC, szalai1 reviewed
@pedro93 static assets should go to https://github.com/datahub-project/static-assets
AFAIK

2022-09-12 16:58 UTC, aditya-radhakrishnan approved these changes
LGTM! @jjoyce0510 can you confirm whether static assets should stay in the imgs directory or be moved to the other repo?

2022-09-14 17:20 UTC, maggiehays requested changes
@pedro93 This is an AWESOME improvement to the existing guide - much easier to follow and approable. Left a couple of comments, but otherwise this is 🔥

2022-09-14 17:20 UTC, maggiehays commented on docs/authentication/personal-access-tokens.md
> +![](../imgs/pats/token-creation-form.png)
Couple of nit-picks for consistency with other guides & improved readability:

* images should be stored in https://github.com/datahub-project/static-assets
*  please use HTML to embed images so we can size down (70%) & center-align:

```
<p align="center">
  <img width="70%"  src="https://raw.githubusercontent.com/datahub-project/static-assets/master/imgs/token-creation-form.png"/>
</p>
```

2022-09-14 17:20 UTC, maggiehays commented on docs/authentication/personal-access-tokens.md
> +![](../imgs/pats/filled-out-form.png)
Same here - move to `/static-assets` repo & embed with HTML

2022-09-14 17:20 UTC, maggiehays commented on docs/authentication/personal-access-tokens.md
> +![](../imgs/pats/token-info.png)
Same here - move to `/static-assets` repo & embed with HTML

2022-09-14 17:20 UTC, maggiehays commented on docs/authentication/personal-access-tokens.md
> + <!-- Use the following format:
Let's remove commented out details from the template unless they capture doc-specifc details

2022-09-14 17:51 UTC, pedro93 commented
Comments addressed, this PR depends on https://github.com/datahub-project/static-assets/pull/8/files being merged.

2022-09-14 17:55 UTC, maggiehays approved these changes

2022-09-14 18:13 UTC, merged