feat(docs): Improve documentation about Search
datahub-project/datahub pull request #5889
Opened 2022-09-09 13:41 UTC by szalai1

(cherry picked from commit ec016b4abff6bdc5ae753f14cca4746944b7ed82)

## Checklist
- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

2022-09-09 17:52 UTC, jjoyce0510 approved these changes
I made various changes directly as commits on this PR. Overall looking good! 

Once @gabe-lyons 's advanced search features land, we'll need to come back and revisit this

2022-09-12 20:31 UTC, maggiehays commented
@szalai1 @jjoyce0510 we get a lot of questions from OSS about how Search results are displayed - can we add in those details in FAQ?

2022-09-12 20:40 UTC, maggiehays requested changes
This is looking great!! Left a few comments/requested changes for you to consider

2022-09-12 20:40 UTC, maggiehays commented on docs/how/search.md
> +![](https://github.com/datahub-project/static-assets/blob/main/imgs/search-landingpage.png?raw=true)
Small nit-pick for consistency with other guides & improved readability - please use HTML to embed images so we can size down (70%) & center-align: 

```
<p align="center">
  <img width="70%"  src="https://github.com/datahub-project/static-assets/blob/main/imgs/search-landingpage.png?raw=true"/>
</p>
```

2022-09-12 20:40 UTC, maggiehays commented on docs/how/search.md
> +![](https://raw.githubusercontent.com/datahub-project/static-assets/main/imgs/filters_highlighted.png)
Same here - please use HTML to embed:
```
<p align="center">
  <img width="70%"  src="https://raw.githubusercontent.com/datahub-project/static-assets/main/imgs/filters_highlighted.png"/>
</p>
```

2022-09-12 20:40 UTC, maggiehays commented on docs/how/search.md
> +Search is available for all users. Although Search works out of the box, the more relevant data you ingest, the better the results are.
Let's elaborate on this - what is relevant data here? What types of metadata improve Search results?

2022-09-12 20:40 UTC, maggiehays commented on docs/how/search.md
> +<!-- This section should provide a plain-language overview of feature. Consider the following:
Let's remove commented-out template details unless they are proving specific value in how to interpret the doc

2022-09-20 15:29 UTC, maggiehays approved these changes
Look great!

2022-09-27 22:50 UTC, hsheth2 commented
The formatting of the use case list is pretty ugly - not super readable, extra `*` characters, some headers are italics and others not


<img width="1030" alt="image" src="https://user-images.githubusercontent.com/12566801/192651115-4946bb77-861d-4ba6-845d-a5368e6cf3dc.png">

2022-10-03 07:35 UTC, merged