docs: add sync status feature guide
datahub-project/datahub pull request #5897
Opened 2022-09-09 21:35 UTC by hsheth2

Waiting on https://github.com/datahub-project/static-assets/pull/6 for screenshots.

## Checklist
- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

2022-09-11 02:53 UTC, shirshanka commented
looks like doc build failed

2022-09-14 17:10 UTC, maggiehays requested changes

2022-09-14 17:10 UTC, maggiehays commented on docs/sync-status.md
> +We'll automatically assign a color based on the sync status recency, with green indicating a fresh entity and red indicating a stale one.
Let's elaborate here on the underlying business logic that determines the colors.

2022-09-14 17:10 UTC, maggiehays commented on docs/sync-status.md
> +The last synchronized date is computed as the most recent edit to the entity, excluding edits done through the UI.
Let's elaborate on this a little bit - what counts as an edit? What happens in there's an ingestion run, but no net-new edits? if someone sees that something is out of sync, what actions can they take to get it back into sync?

2022-09-14 17:10 UTC, maggiehays commented on docs/sync-status.md
> +![sync status](https://raw.githubusercontent.com/datahub-project/static-assets/master/imgs/sync-status.png)
Small nit-pick for consistency with other guides & improved readability - please use HTML to embed images so we can size down (70%) & center-align: 

```
<p align="center">
  <img width="70%"  src="https://raw.githubusercontent.com/datahub-project/static-assets/master/imgs/sync-status.png"/>
</p>
```

2022-09-14 17:10 UTC, maggiehays commented on docs/sync-status.md
> +![hover card](https://raw.githubusercontent.com/datahub-project/static-assets/master/imgs/sync-status-hover-card.png)
Same thing here - please use HTML for consistency in 70% sizing & center alignment

2022-10-05 17:17 UTC, laulpogan commented
@shirshanka per @hsheth2 this PR is good to go, we just need your approval

2022-10-14 19:35 UTC, maggiehays approved these changes

2022-10-14 22:07 UTC, merged