feat(kakfa-connect): generic connector
datahub-project/datahub pull request #6173
Opened 2022-10-11 23:36 UTC by BoyuanZhangDE

## Checklist
- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

2022-10-11 23:37 UTC, BoyuanZhangDE commented
Make kafka-connect ingestion support connectors other than confluent JDBC connector and debezium connector

2022-10-13 23:20 UTC, hsheth2 requested changes
Looking good.

If possible, it'd be great to add some tests for this as well :)

2022-10-13 23:20 UTC, hsheth2 commented on metadata-ingestion/src/datahub/ingestion/source/kafka_connect.py
> +        default=None,
```suggestion
    generic_connectors: List[GenericConnectorConfig] = Field(
        default=[]],
```

2022-10-13 23:20 UTC, hsheth2 commented on metadata-ingestion/src/datahub/ingestion/source/kafka_connect.py
> +                            f"Detected undefined connector {connector_manifest.name}, but user defined no customized connectors. Please refer to Kafka Connect ingestion recipe to define this customiz
this error checking becomes redundant given the check below, once the default is changed to []

2022-10-14 03:57 UTC, BoyuanZhangDE commented
> Looking good.
> 
> If possible, it'd be great to add some tests for this as well :)

will do!

2022-10-25 06:02 UTC, hsheth2 approved these changes

2022-10-25 17:31 UTC, merged