Elasticsearch setup analytics
datahub-project/datahub pull request #6291
Opened 2022-10-26 13:53 UTC by djordje-mijatovic

## Checklist
- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

This will fix the following error when specifying DATAHUB_ANALYTICS_ENABLED=false:

> going to use protocol: https
> going to use elastic headers based on username and password
> going to use prefix: 'datahub-abc_'
> 
> datahub_analytics_enabled: false
> 2022/10/26 13:42:46 Command exited with error: exit status 1

2022-10-26 15:18 UTC, mattmatravers commented
This should probably be committed as `fix(elasticsearch): elasticsearch-setup-job fails when DATAHUB_ANALYTICS_ENABLED=false`

2022-10-26 15:18 UTC, mattmatravers approved these changes
Looks great - I've tested this locally and it fixes the problem

2022-10-26 15:29 UTC, mattmatravers requested changes
Whoops - one character fix!

2022-10-26 15:29 UTC, mattmatravers commented on docker/elasticsearch-setup/create-indices.sh
> +  DATAHUB_USAGE_EVENT_INDEX_RESPONSE_CODE=$(curl "${CURL_ARGS[@]}" -o /dev/null -w "%{http_code}" "$ELASTICSEARCH_URL/cat/indices/${PREFIX}datahub_usage_event")
```suggestion
  DATAHUB_USAGE_EVENT_INDEX_RESPONSE_CODE=$(curl "${CURL_ARGS[@]}" -o /dev/null -w "%{http_code}" "$ELASTICSEARCH_URL/_cat/indices/${PREFIX}datahub_usage_event")
```

As per https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html, the correct url is `_cat/indices/`

2022-10-26 17:47 UTC, mattmatravers commented
For context, this first broke in https://github.com/datahub-project/datahub/pull/5502

2022-10-27 08:47 UTC, mattmatravers approved these changes
Looks good and I've tested the code paths locally

2022-10-28 15:04 UTC, david-leifker approved these changes

2022-10-31 20:50 UTC, jjoyce0510 approved these changes

2022-10-31 20:50 UTC, merged