fix(ingestion/vertica): support ingestion of tables with precision field in timestamp values in Vertica
datahub-project/datahub pull request #6295
Opened 2022-10-26 20:48 UTC by inancdokurel

This PR aims to fix the problem referred in the #5295

It is not a perfect fix, however it allows timestamp fields with precision values to be ingested into Datahub 

## Checklist
- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

2022-11-15 09:39 UTC, inancdokurel commented
Anybody willing to review and provide comments?

2022-12-06 23:22 UTC, hsheth2 requested changes
Sorry about the delay in review

This mostly looks good, but I've added two small comments

2022-12-06 23:22 UTC, hsheth2 commented on metadata-ingestion/src/datahub/ingestion/source/sql/vertica.py
> +    self.ischema_names["TIMESTAMP"] = TIMESTAMP_WITH_PRECISION
```suggestion
    self.ischema_names["TIMESTAMP"] = TIMESTAMPWP
```

2022-12-06 23:22 UTC, hsheth2 commented on metadata-ingestion/src/datahub/ingestion/source/sql/vertica.py
> +def TIMESTAMP_WITH_PRECISION(*args, **kwargs):
this method isn't necessary - see below

2022-12-07 15:47 UTC, inancdokurel commented on metadata-ingestion/src/datahub/ingestion/source/sql/vertica.py
> +    self.ischema_names["TIMESTAMP"] = TIMESTAMP_WITH_PRECISION
changed in the latest commit

2022-12-07 23:10 UTC, merged