Added I AM auth for Opensearch
datahub-project/datahub pull request #6370
Opened 2022-11-05 04:11 UTC by syedzoherer

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [X] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

2022-11-05 04:29 UTC, syedzoherer commented
To access Opensearch with IAM auth, request needs to be signed with IAM auth. This change will allow users requests to be signed if OPENSEARCH_USE_AWS_IAM_AUTH is set to true.

2022-11-14 20:37 UTC, RyanHolstien requested changes

2022-11-18 18:59 UTC, syedzoherer commented on metadata-service/factories/src/main/java/com/linkedin/gms/factory/common/RestHighLevelClientFactory.java
> +    } else if ((username != null && password != null) || opensearchUseAwsIamAuth) {
Code refactor and removed default Region.

2022-11-18 21:36 UTC, RyanHolstien commented on metadata-service/factories/src/main/java/com/linkedin/gms/factory/common/RestHighLevelClientFactory.java
> +        if(opensearchUseAwsIamAuth) {
Fix checkstyle, needs a space after if

2022-11-18 22:48 UTC, syedzoherer commented on metadata-service/factories/src/main/java/com/linkedin/gms/factory/common/RestHighLevelClientFactory.java
> +        if(opensearchUseAwsIamAuth) {
Fixed.

2022-11-22 16:48 UTC, RyanHolstien approved these changes

2022-11-22 16:49 UTC, merged