fix(config): unify the handling of boolean environment variables
datahub-project/datahub pull request #6684
Opened 2022-12-07 23:00 UTC by Masterchen09

When I have tried to set the environment variable DATAHUB_SKIP_CONFIG, I have noticed that the handling of the boolean environment variables (DATAHUB_SKIP_CONFIG, DATAHUB_DEBUG and DATAHUB_TELEMETRY_ENABLED) are quite different: For example the DATAHUB_SKIP_CONFIG variable had to be set to "True" to be true, while the DATAHUB_DEBUG would also be treated as true with the value "false" (the string "false" is a truthy value in Python).

This PR changes/fixes this behaviour by converting all boolean environment variables to lowercase first and comparing them to the strings "true" and "1" (e.g., [here](https://github.com/datahub-project/datahub/blob/3758bcbe348082ea511d8605e3e01e18742283dd/metadata-ingestion/tests/conftest.py#L9) the value "1" is assigned to DATAHUB_DEBUG, therefore the value "1" should also be handled as true).

## Checklist

- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [x] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [x] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

2022-12-07 23:15 UTC, hsheth2 requested changes
Given the copy-paste here, it'd be better to create a tiny helper method for this

2022-12-08 21:35 UTC, Masterchen09 commented
There is a utility function now, I hope cli_utils is the right place for it. There is already something related to environment variables in it, therefore I think it should be fine.

2022-12-08 22:06 UTC, hsheth2 approved these changes
LGTM!

Agree that the cli_utils file seems like a good place for this :)

2022-12-08 23:00 UTC, jjoyce0510 approved these changes
Wonderful PR. Great craftsmanship!

2022-12-08 23:00 UTC, merged