Allows sql_lineage_parser_impl.py to return the original name of entities
datahub-project/datahub pull request #6739
Opened 2022-12-12 20:18 UTC by PatrickfBraz

## Allows sqllineage to return the original name of entities

The [sqllineage](https://github.com/reata/sqllineage) package has been used by the project to build the data lineage. However, the package returns by default the names of the tables and views in lowercase. Therefore, the objective of this PR is to modify the SQL parser that uses this package so that it returns the original names of the entities.

### More details

Previously, the code called the table model or schemas using their '__str__' descriptors. However, it is possible to notice in the [model](https://github.com/reata/sqllineage/blob/master/sqllineage/core/models.py#L35) that there is the possibility of searching for the original values ​​of the names of tables or schemes. With this, it is possible to obtain names that were previously not lowercase.

## Checklist

- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

2022-12-12 20:32 UTC, PatrickfBraz commented
@treff7es @anshbansal 
This modification can break [this code](https://github.com/PatrickfBraz/datahub/blob/master/metadata-ingestion/src/datahub/utilities/sql_lineage_parser_impl.py#L57), but I don't know how to test it correctly.

2022-12-12 21:12 UTC, treff7es requested changes

2022-12-13 11:37 UTC, PatrickfBraz commented on metadata-ingestion/src/datahub/utilities/sql_lineage_parser_impl.py
> +            table_normalized = re.sub(r"^<default>.", "", table.raw_name)
Yes!! I will do that!

2022-12-13 13:05 UTC, PatrickfBraz commented on metadata-ingestion/src/datahub/utilities/sql_lineage_parser_impl.py
> +            table_normalized = re.sub(r"^<default>.", "", table.raw_name)
@treff7es Can you have a look?

2022-12-14 13:58 UTC, merged