fix database name contains uppercase
datahub-project/datahub pull request #7209
Opened 2023-02-01 11:16 UTC by kpretty

Fix the ingestion failure when the database name contains uppercase, and the package library name does not exist
#7208 

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

2023-02-01 13:20 UTC, mayurinehate reviewed
This should not be needed for MySQL in latest DataHub version.

2023-02-01 23:16 UTC, jjoyce0510 commented
This seems dangerous, as it will change existing URNs for folks. This means broken links, duplicate entities, and worse.

2023-02-02 03:15 UTC, anshbansal requested changes
This is a breaking change. Do not merge it as it is.

2023-02-02 06:16 UTC, mayurinehate commented
This change is not needed, as the reported issue is already fixed for mysql through two tier sql datasources in latest versions.

2023-02-02 06:16 UTC, closed without merging