docs(): great expectations ingestion quickstart guide
datahub-project/datahub pull request #7507
Opened 2023-03-07 08:06 UTC by pabloochoaa

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

2023-03-08 00:11 UTC, maggiehays commented
Hey @pabloochoaa! Thanks SO MUCH for contributing this - I'm on point to run through it to review readability/complexity; I'm hoping to get through review this week.

2025-02-07 08:46 UTC, yoonhyejin commented
Hey @pabloochoaa! Thanks for raising the PR -- overall seems good, but there are a few points that need to be adjusted : 

* could you add .md files to `docs-website/sidebars.js` so we can access the files from the sidebar? 
* could you add img files to [static-assets](https://github.com/datahub-project/static-assets) repo and refer images like below? 

```
<p align="center">
  <img width="70%"  src="https://raw.githubusercontent.com/datahub-project/static-assets/main/imgs/impact-analysis-export-full-list.png"/>
</p>
```

you can [Docs practices guide](https://github.com/datahub-project/datahub/tree/master/docs#docs-best-practices) for more details, but feel free to reach out if you have any questions!

2025-02-07 08:47 UTC, yoonhyejin requested changes
Hey @pabloochoaa! Thanks for raising the PR -- overall seems good, but there are a few points that need to be adjusted :

could you add .md files to docs-website/sidebars.js so we can access the files from the sidebar?
could you add img files to [static-assets](https://github.com/datahub-project/static-assets) repo and refer images like below?
```
<p align="center">
  <img width="70%"  src="https://raw.githubusercontent.com/datahub-project/static-assets/main/imgs/impact-analysis-export-full-list.png"/>
</p>
```
you can check [docs practices guide](https://github.com/datahub-project/datahub/tree/master/docs#docs-best-practices) for more details, but feel free to reach out if you have any questions!

2025-06-27 09:08 UTC, yoonhyejin commented
<!-- PR Nanny Status -->
<!-- PR_NANNY_STATE: {"is_active":true,"activated_by":"yoonhyejin","last_updated":"2025-06-27T18:08:01.279194","total_retries":0,"has_escalated_jobs":false,"retry_details":{"retrying":{},"recovered":{},"escalated":{}},"version":1,"escalated_at":null,"last_commit_sha":"c7fcdb56624a37be29695849575894d6bf8544b1","lease":null} -->

## 🤖 PR Nanny Status: ✅ All Checks Passing
*Last updated: 2025-06-27 09:08:01 UTC / 2025-06-27 18:08:01 KST*

I'm monitoring this PR and all critical checks are currently passing.

I'll automatically retry any critical checks that fail in the future.

---
**🎯 Browser tab chaos? Get terminal clarity** - [Get PR Nanny](https://github.com/acryldata/pr-nanny#readme)

2026-06-06 12:50 UTC, lakshay-nasa commented
Hey @pabloochoaa - thank you for writing this, and sorry it sat so long without a real reply.

Coming back to it now: Great Expectations shipped 1.0 since you wrote this, which retired the whole CLI flow this guide is built on (commands like `datasource new` don't exist anymore). The DataHub - GE integration itself is already documented here: https://docs.datahub.com/docs/metadata-ingestion/integration_docs/great-expectations - so I'm going to close this one out rather than revive a guide on the old workflow.

Appreciate the effort you put in here.

2026-06-06 12:50 UTC, closed without merging