feat(ingest/looker): Record observed lineage timestamps for Looker and LookML sources
datahub-project/datahub pull request #7735
Opened 2023-03-31 16:17 UTC by ANich

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
~- [ ] Links to related issues (if applicable)~
- [x] Tests for the changes have been added/updated (if applicable)
~- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.~
~- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)~

2023-04-18 02:47 UTC, hsheth2 requested changes

2023-04-18 02:47 UTC, hsheth2 commented on metadata-ingestion/src/datahub/ingestion/source/looker/looker_common.py
> +                            actor="urn:li:corpuser:datahub",
it'd be good to extract this out into a constant

2023-04-18 02:47 UTC, hsheth2 commented on metadata-ingestion/src/datahub/ingestion/source/looker/looker_common.py
> +from datahub.metadata.com.linkedin.pegasus2avro.common import AuditStamp
looks like linter doesn't like the import sorting here

2023-06-07 17:26 UTC, laulpogan commented
@ANich - we haven't seen movement on this PR for a little while- are you still interested in contributing? If so, please let us know within the week, or we'll need to close this one for inactivity.

2023-07-19 16:32 UTC, ANich commented
> @ANich - we haven't seen movement on this PR for a little while- are you still interested in contributing? If so, please let us know within the week, or we'll need to close this one for inactivity.

Hey @laulpogan @anshbansal I'll pick this back up in the next couple days if that's okay. Will ping for a re-review

2023-08-15 22:23 UTC, hsheth2 reviewed
We should to add tz to now() calls, but otherwise lgtm

2023-08-15 22:23 UTC, hsheth2 commented on metadata-ingestion/src/datahub/ingestion/source/looker/looker_common.py
> +            observed_lineage_ts = datetime.datetime.now()
```suggestion
            observed_lineage_ts = datetime.datetime.now(tz=timezone.utc)
```

2023-08-15 22:23 UTC, hsheth2 commented on metadata-ingestion/src/datahub/ingestion/source/looker/lookml_source.py
> +        observed_lineage_ts = datetime.now()
needs tz

2023-08-17 14:38 UTC, ANich commented on metadata-ingestion/src/datahub/ingestion/source/looker/looker_common.py
> +            observed_lineage_ts = datetime.datetime.now()
Updated! Thanks for the review

2023-08-24 09:17 UTC, merged

2023-08-24 09:17 UTC, anshbansal commented
cypress test failures unrelated so merging.