fix(ingestion/powerbi): fix fetch reports for workspace
datahub-project/datahub pull request #8021
Opened 2023-05-11 14:34 UTC by shubhamjagtap639

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

2023-05-16 05:50 UTC, mohdsiddique requested changes

2023-05-16 05:50 UTC, mohdsiddique commented on metadata-ingestion/src/datahub/ingestion/source/powerbi/rest_api_wrapper/data_resolver.py
> +        if response.status_code != 200:
Let's add a common function to log debug messages if status_code is not equal to 200

2023-05-16 11:32 UTC, mohdsiddique approved these changes
LGTM

2023-05-18 19:46 UTC, hsheth2 reviewed
few nits but otherwise lgtm

2023-05-18 19:46 UTC, hsheth2 commented on metadata-ingestion/src/datahub/ingestion/source/powerbi/rest_api_wrapper/data_resolver.py
> +        logger.debug(message)
should this be an info level message?

2023-05-18 19:46 UTC, hsheth2 commented on metadata-ingestion/src/datahub/ingestion/source/powerbi/rest_api_wrapper/data_resolver.py
> +    @staticmethod
make this a function outside the class rather than static method in the class

2023-05-18 19:46 UTC, hsheth2 commented on metadata-ingestion/tests/integration/powerbi/test_powerbi.py
> +    Here we don't need to run the pipeline. We need to verify all reports are getting fetch in case any page request failed
```suggestion
    Test that all reports are fetched even if a single page request fails
```

2023-05-19 21:30 UTC, hsheth2 approved these changes

2023-05-20 01:02 UTC, merged