Docs/dh projects
datahub-project/datahub pull request #8422
Opened 2023-07-14 07:04 UTC by yoonhyejin

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

2023-07-17 16:53 UTC, shirshanka commented on docs-website/src/pages/docs/index.js
> +const gitLinkContent = [
links are incorrect on this list

2023-07-17 16:54 UTC, shirshanka commented on docs-website/src/pages/docs/index.js
> +const gitLinkContent = [
missing dbt impact analysis repo

2023-07-17 16:54 UTC, shirshanka requested changes
changes needed to the gitlink section

2023-07-18 02:17 UTC, yoonhyejin commented on docs-website/src/pages/docs/index.js
> +const gitLinkContent = [
🤦‍♀️ i can't believe i missed this

2023-08-04 02:22 UTC, hsheth2 approved these changes

2023-08-04 02:22 UTC, hsheth2 commented on README.md
> +- [datahub-tools](https://github.com/makenotion/datahub-tools) : A python quasi-client (and tools) that interacts with DataHub GraphQL endpoints, build by Notion
```suggestion
- [datahub-tools](https://github.com/makenotion/datahub-tools) : Additional python tools to interact with the DataHub GraphQL endpoints, built by Notion
```

2023-08-04 19:35 UTC, merged