fix(powerbi): fix access token expiry
datahub-project/datahub pull request #8680
Opened 2023-08-21 15:02 UTC by elish7lapid

Powerbi returns an expiry time for the access
token which is currently ignored.
This causes all api calls to fail after 60 minutes, which is the timeout returned by PowerBI.
This commit fixes the bug by creating a new token
once the old one expires.

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

2023-08-24 10:07 UTC, siddiquebagwan-gslab requested changes
Looks overall good, just one comment

2023-08-24 10:07 UTC, siddiquebagwan-gslab commented on metadata-ingestion/src/datahub/ingestion/source/powerbi/rest_api_wrapper/data_resolver.py
> +        if self.__access_token is not None and self.__access_token_expiry_time > datetime.now():
Could you please put the expiry condition check in a method `is_token_expire()`

2023-08-27 06:50 UTC, elish7lapid commented
@siddiquebagwan-gslab fixed

2023-08-29 05:28 UTC, siddiquebagwan-gslab approved these changes
LGTM

2023-08-30 08:09 UTC, elish7lapid commented
@siddiquebagwan-gslab seems that CI is stuck - is there a way to trigger it to run? (I tried to close and reopen the PR but that just removed your approval so now I need you to approve again)

2023-09-12 21:30 UTC, hsheth2 approved these changes

2023-09-14 12:33 UTC, siddiquebagwan-gslab commented
> @siddiquebagwan-gslab seems that CI is stuck - is there a way to trigger it to run? (I tried to close and reopen the PR but that just removed your approval so now I need you to approve again)

Hi @elish7lapid 
Please execute `../gradlew :metadata-ingestion:lintFix` from `metadata-ingestion` directory and fix the lint error

2023-09-26 11:57 UTC, closed without merging