Fix(ingest/bigquery): fix extracting comments from complex types
datahub-project/datahub pull request #8950
Opened 2023-10-04 16:18 UTC by maaaikoool

Closes https://github.com/datahub-project/datahub/issues/8763

Fixes a conditional to extract the field description when the field is part of a record. `SchemaField`s are lower case, while `BigQueryColumn`s have the original column name.

## Checklist

- [X ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [X] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

2023-10-06 06:18 UTC, lusob approved these changes

2023-10-25 12:26 UTC, mayurinehate requested changes
Tested with table having a complex type with uppercase leaf node and able to reproduce the issue.

If the root node of complex type is also in uppercase, the suggested change is required.
Otherwise looks good.

2023-10-25 12:26 UTC, mayurinehate commented on metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
>                              re.sub(r"\[.*?\]\.", "", field.fieldPath, 0, re.MULTILINE)
```suggestion
                            re.sub(r"\[.*?\]\.", "", field.fieldPath.lower(), 0, re.MULTILINE)
```

2023-10-25 13:14 UTC, mayurinehate approved these changes
LGTM

2023-10-26 06:54 UTC, mayurinehate requested changes
@maaaikoool can you please fix the lint ? https://github.com/datahub-project/datahub/actions/runs/6640885066/job/18042206118?pr=8950

2023-10-26 10:45 UTC, mayurinehate approved these changes

2023-10-27 05:01 UTC, hsheth2 approved these changes

2023-10-27 05:01 UTC, merged