OBS-191 | Viewing domains page should not require Manage Domains priv…
datahub-project/datahub pull request #9156
Opened 2023-11-01 06:04 UTC by sumitappt

…ilege

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

2023-11-01 18:05 UTC, jjoyce0510 approved these changes

2023-11-01 18:08 UTC, jjoyce0510 requested changes
Actually this looks incorrect. 

The user should be able to view domains _always_, even if they cannot create domains. 

I should have specified further.

2023-11-02 06:28 UTC, sumitappt commented
> Actually this looks incorrect.
> 
> The user should be able to view domains _always_, even if they cannot create domains.
> 
> I should have specified further.

Got it. We should remove the privilege checks for creating and managing domains since they should always be visible.

2023-11-04 19:07 UTC, jjoyce0510 approved these changes

2023-11-04 19:32 UTC, merged