refactor(ingestion/bigquery): Investigate BigQuery usage from exported metadata slowness
datahub-project/datahub pull request #9247
Opened 2023-11-15 10:00 UTC by shubhamjagtap639

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

2023-11-15 19:24 UTC, asikowitz requested changes
Can you break this down by both? i.e. one timer for sql parsing, another for store_usage_event?

2023-11-18 21:22 UTC, asikowitz approved these changes

2023-11-20 18:17 UTC, hsheth2 approved these changes

2023-11-20 18:17 UTC, hsheth2 commented on metadata-ingestion/src/datahub/utilities/sqlglot_lineage.py
> +        if self.platform in CASE_SENSITIVE_PLATFORMS:
rename to TABLE_CASE_SENSITIVE_PLATFORMS

2023-11-20 18:17 UTC, hsheth2 commented on metadata-ingestion/src/datahub/utilities/bigquery_sql_parser.py
> +class BigQuerySQLParser:
add a comment that this is unused and purely for tests for now

maybe move to the tests/ directory?

2023-12-28 00:35 UTC, hsheth2 commented
@asikowitz would love to get this merged since the changes are good and I don't want them to get stale

2023-12-28 06:34 UTC, asikowitz commented
Thanks for the reminder

2023-12-28 09:54 UTC, merged