feat(ingest/powerbi): powerbi dataset profiling
datahub-project/datahub pull request #9355
Opened 2023-11-30 11:47 UTC by looppi

DAX REST API based profiling implementation to query some details of PowerBI Datasets in the workspace. Does not introduce any breaking changes.

Is this something you would like to accept and include in Datahub or is using the DAX API for gathering information considered not a good practice?

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [x] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

2023-12-18 08:34 UTC, siddiquebagwan requested changes

2023-12-18 08:34 UTC, siddiquebagwan commented on metadata-ingestion/src/datahub/ingestion/source/powerbi/rest_api_wrapper/powerbi_api.py
> +        self.__profiling_resolver = PowerBiDatasetProfilingResolver(
There are only two way to get the metadata from PowerBI either using regular API or Admin API. You can clearly see this segregation in PowerBI Rest API documentation: https://learn.microsoft.com/en-us/rest/api/power-bi/.

As per doc it looks like it comes under regular-api, so please add profile_dataset in base resolver  and provide implementation in both regular and admin resolver (here it is just pass). Invoke the  powerbi_profiler.py from regular api's profile_dataset  method

2023-12-18 08:34 UTC, siddiquebagwan commented on metadata-ingestion/src/datahub/ingestion/source/powerbi/rest_api_wrapper/data_classes.py
> +    min: Optional[str] = None
Better to have MeasureProfiling dataclass and add the reference here

2023-12-18 08:34 UTC, siddiquebagwan commented on metadata-ingestion/docs/sources/powerbi/powerbi_pre.md
> +The profiling implementation is done through querying [DAX query endpoint](https://learn.microsoft.com/en-us/rest/api/power-bi/datasets/execute-queries). Therefore the principal needs to have permiss
Additional documentation need to be added: 

1. Please also check this doc: https://datahubproject.io/docs/quick-ingestion-guides/powerbi/setup and add/update any steps if any specific permission is required for profiling. The markdown file is available at `docs/quick-ingestion-guides/powerbi/setup.md`
2. On Source class add decorator `@capability(
    SourceCapability.DATA_PROFILING,
    "Optionally enabled via configuration `profiling.enabled`",
)`

2024-01-04 07:36 UTC, looppi commented
Thank you for the feedback! I'll start working with this asap.

2024-01-18 22:01 UTC, hsheth2 commented
@sid-acryl can you take another look at this PR?

2024-02-28 06:12 UTC, sid-acryl requested changes

2024-02-28 06:12 UTC, sid-acryl commented on metadata-ingestion/src/datahub/ingestion/source/powerbi/rest_api_wrapper/profiling_utils.py
> +def get_column_name(table_and_col: str) -> str:
Make it -> Optional[str]

2024-02-28 17:42 UTC, hsheth2 commented on metadata-ingestion/src/datahub/ingestion/source/powerbi/rest_api_wrapper/data_resolver.py
> +            rows = data["results"][0]["tables"][0]["rows"]
it looks like they're already catching KeyError below, so it should be ok

2024-02-28 18:50 UTC, looppi commented
Thank you for the review and feedback! I'll continue working on this still this week.

2024-05-10 12:03 UTC, looppi commented on metadata-ingestion/docs/sources/powerbi/powerbi_pre.md
Sorry for the delay, I added mention that the dataset profiling is not available through the Admin API

2024-05-24 09:55 UTC, sid-acryl approved these changes
LGTM

2024-05-24 19:11 UTC, hsheth2 approved these changes

2024-06-28 21:50 UTC, merged