Reduce GraphQL Logs to warning for circuit breaker
datahub-project/datahub pull request #9436
Opened 2023-12-11 19:05 UTC by arunvasudevan

## Checklist

- [X ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

More context on this slack thread - https://datahubspace.slack.com/archives/C02AD211493/p1701473704104679?thread_ts=1699981235.411909&cid=C02AD211493

Reduce the GraphQL logging to avoid cloud watch 256KB limit when circuit breaker is running on MWAA

2023-12-12 08:36 UTC, treff7es requested changes

2023-12-12 08:36 UTC, treff7es commented on metadata-ingestion/src/datahub/api/circuit_breaker/assertion_circuit_breaker.py
> +from gql.transport.requests import log as requests_logger
Linter fails on this as imports should be at the top.

2023-12-12 08:36 UTC, treff7es commented on metadata-ingestion/src/datahub/api/circuit_breaker/assertion_circuit_breaker.py
> +requests_logger.setLevel(logging.WARNING)
Can you move this to the abstract class' init and then this change would be available for all the circuit breakers.

2023-12-13 21:20 UTC, hsheth2 approved these changes
LGTM

2023-12-13 22:01 UTC, treff7es approved these changes

2023-12-13 22:02 UTC, merged